### ISSUE TITLE
I need change min SDK to 19

### ISSUE THREAD

**Issue by AlirezaDaryani** [abbyysdk/RTR-SDK.Android#18] opened 2020-06-29 12:17 UTC
I use release 8 SDK for my app, but now i need use it for api 19+.

I just need text capture.

what release i can use for this min sdk?

**Comment by IvanShafran** [comment] 2020-06-29 12:45
Hello, @AlirezaDaryani !

You could use the release 7 SDK. However, keep in mind that we officially dropped support for 19 and 20 Android API a year ago. We set this restriction in code since the release 8 SDK to match documentation, so please consider moving to 21 min API.

Have a nice day!

**Comment by AlirezaDaryani** [comment] 2020-06-29 13:09
I do this but get this error, for my project i need min sdk 19

Unspecified error while loading the engine. See logcat for details.

**Comment by IvanShafran** [comment] 2020-06-29 13:16
@AlirezaDaryani , probably there is an error with a license or assets. Could you post the logcat? Also, please check [this instruction](https://help.abbyy.com/en-us/mobilecapturesdk/1/android_help/android.configureyourproject).

**Comment by AlirezaDaryani** [comment] 2020-06-29 14:55
this is my logcat :

 [ 06-29 19:21:08.708  2941: 2941 E/Text Capture
    (RTR SDK) ]
    Error loading ABBYY RTR SDK:
    java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libMobileOCR.so" needed by "libabbyy-rtr-sdk.so"; caused by could not load library "libFineObj.so" needed by "libMobileOCR.so"; caused by cannot locate symbol "strtof" referenced by "libFineObj.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:365)
        at java.lang.System.loadLibrary(System.java:526)
        at com.abbyy.mobile.ocr4.Engine.loadNativeLibrary(Engine.java:365)
        at com.abbyy.mobile.rtr.EngineImpl.create(EngineImpl.java:50)
        at com.abbyy.mobile.rtr.Engine.load(Engine.java:26)
        at com.abbyy.mobile.sample.MainActivity.createTextCaptureService(MainActivity.java:488)
        at com.abbyy.mobile.sample.MainActivity.onCreate(MainActivity.java:812)
        at android.app.Activity.performCreate(Activity.java:5451)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2386)
        at android.app.ActivityThread.access$900(ActivityThread.java:169)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1277)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5476)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by IvanShafran** [comment] 2020-06-29 15:09
Please, try this:
"Go to Run -> Edit Configurations -> Profiling, and disable "Enable advanced profiling""

From: https://stackoverflow.com/questions/43745312/unsatisfiedlinkerror-dlopen-failed-cannot-locate-symbol-strtof-referenced-by

And to be sure, did you get the error while running the release 7 on Android 19-20?

**Comment by AlirezaDaryani** [comment] 2020-06-29 16:02
yes i get this error in Samsung S3 with android   4.4.2
I will test it and will come here again.

**Comment by AlirezaDaryani** [comment] 2020-06-29 16:16
Do not work for me...

**Comment by IvanShafran** [comment] 2020-06-29 17:29
Could you try to run on Android API 21 or higher, and post results? An emulator is okay if you don't have a real device.

Also, additionally to disabling "advanced profiling" try:
- File->Invalidate caches and restart
- delete the application from the device

These steps can help when you are dealing with "so" problems.

**Comment by AlirezaDaryani** [comment] 2020-06-30 06:54
@IvanShafran 
this solution doesn't work ...

I test app in api 21+ and it working well.
Please help me to resolve this issue.

**Comment by IvanShafran** [comment] 2020-06-30 11:08
Yeah, I reproduced it myself. Unfortunately, min SDK 21 is the restriction of native libraries build tools. Therefore it is an official min SDK that is supported.

Is min SDK 19 your business requirement? If it is I can suggest reaching our customer support.

**Comment by AlirezaDaryani** [comment] 2020-07-01 07:06
Yes its is required in my app and i need to reach this functionality.

How can I reach customer support?

**Comment by IvanShafran** [comment] 2020-07-01 18:22
You could submit a request to support here: https://support.abbyy.com/hc/en-us/requests/new

**Closed as completed by IvanShafran** 2020-07-01 18:22 UTC
