### ISSUE TITLE
Issue when scan repetitly

### ISSUE THREAD

**Issue by gregcho** [abbyysdk/RTR-SDK.Android#16] opened 2019-09-16 01:45 UTC
```
@Override
public void onError( Exception e )
{
// Recognition process errors handling
Log.e( TAG, "Recognition error: " + e.getMessage(), e );

publishProgress( "Recognition error: " + e.getMessage() );
}
```
java.lang.NullPointerException: Attempt to invoke interface method 'void com.abbyy.mobile.ocr4.RecognitionManager.setRecognizerThreadsCount(int)' on a null object reference

**Comment by aleksey-ka** [comment] 2019-09-16 08:50
Looking at the evidence it's hard to guess what actually went wrong. I would say you are trying to work with something deinitialized (multithreading issue?) . If you want a solution on our side, it would be helpful if you provided a more detailed description or a simple sample application to reproduce the error.

The error message is not very informative. Thank you for the feedback.

**Comment by gregcho** [comment] 2019-09-16 09:07
I'm using sample-coreapi sample in android sdk. 
(abbyy-mi-rtr-sdk-5.0.6.49-Android-ExtendedDC)

Maybe you can find same issue when you repeat recognition approximately 10times.
1. Open and recognize image
2. select image
3. recognize

Here my code.
**IRecognitionCoreAPI recognitionCoreAPI = engine.createRecognitionCoreAPI();
recognitionCoreAPI.getProcessingSettings().setProcessingThreadsCount(0);
recognitionCoreAPI.getTextRecognitionSettings().setRecognitionLanguage( Language.valueOf( "English" ));
blocks = recognitionCoreAPI.recognizeText( image, callback );// exception here **

If you need more information, please tell me
Thanks.

**Comment by aleksey-ka** [comment] 2019-09-16 09:11
Are all these 10 recognitions performed sequentially on the same thread? Or each on a new background thread? Is there any overlap?

**Comment by gregcho** [comment] 2019-09-16 09:17
sequentially on the same thread.

I have called like that.

**cancelActiveRecognitionTask();
activeRecognitionTask = new TextRecognitionTask( engine, bitmap, recognitionLanguage, this );
activeRecognitionTask.execute().get();**

**Comment by aleksey-ka** [comment] 2019-09-16 09:20
Thank you! We'll try to reproduce the issue

**Comment by aleksey-ka** [comment] 2019-09-17 08:15
We've reproduced the problem on our side. It seems to be an issue in the sample code:

Instances of **IRecognitionCoreAPI** are not properly deinitialized in the sample application. These are **AutoClosable** objects and should be closed after use. If you patch **doInBackground** method in **TextRecognitionTask** class as shown below (see try-with-resources statement), the problem should be solved:

```
		@Override
		protected String doInBackground( Void... params )
		{
			// The 'Abbyy RTR SDK Core API' object to be used in this sample application
fix ==>			try( IRecognitionCoreAPI recognitionCoreAPI = engine.createRecognitionCoreAPI() ) {

				…
				return resultText.toString();
			}
		}
```

**Comment by gregcho** [comment] 2019-09-18 00:47
Thanks, your reply.
I have 1 more question.
How to initialize Instances of IRecognitionCoreAPI after exception?
I want to try recognition an image until it is recognized even 10times

**Comment by aleksey-ka** [comment] 2019-09-18 09:09
If it is a recoverable exception, just create a new instance of RecognitionCoreAPI object (or continue using your existing object if you catch the exception inside the try-with-resources block). If it is unrecoverable - you will not be able to recognize the image, no matter how many times you try

As per the issue. It has been fixed in a downstream repository and will eventually be pushed to GitHub

Thank you for your feedback

**Closed as completed by aleksey-ka** 2019-09-18 09:09 UTC
